# -*- coding: utf-8 -*-

# app.debug
DEBUG = True

# API & JSON
JSON_AS_ASCII = False
JSONIFY_PRETTYPRINT_REGULAR = None
JSON_SORT_KEYS = None

# database
SQLALCHEMY_DATABASE_URI = None
SQLALCHEMY_BINDS = {
}

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True

